### PR TITLE
Tracker requirement tooltips

### PR DESCRIPTION
**Pull request by robojumper**
## What does this address?

Adds tooltips explaining the required items for each check.

grafik

## How did/do you test these changes?

* This PR includes some test code
* Spot checking
* Needs more tests with more varied settings

## Notes

* A straightforward future extension would be adding tooltips for exits too.
* If entrances are randomized and revealed, the tooltips will take all of that into account, but if you e.g. haven't found a dungeon entrance yet, then all locations in it will be "Impossible (please discover an entrance first)" since there is no possible set of items that will put the locations in logic.
* The same extends to the Bazaar, if you haven't found the Bazaar yet, all requirements that depend on a bottle or a shield will be "Impossible (please discover an entrance first)".

### CODE REVIEW

**Comment by CovenEsme** [comment]
When hovering over a location, if the tooltip box is big enough to appear underneath my cursor, it'll flash up for about half a second before disappearing

https://github.com/mint-choc-chip-skyblade/sshd-rando/assets/84377742/abad5499-43f3-4ee8-a8ee-79504aee91e3

**Comment by YourAverageLink** [comment]
> When hovering over a location, if the tooltip box is big enough to appear underneath my cursor, it'll flash up for about half a second before disappearing
> tracker-tooltips.mp4

Ugh, this seems to be another case of the tooltips being weirdly different on different operating systems. On my end, the tooltips show up entirely below the check name.

**Review by CovenEsme — COMMENTED** [review]
lg2m - besides some logic expression ordering stuff that's not critical

Not sure if this is "done" yet. Let me know when you want it merging

**Comment by robojumper** [comment]
> logic expression ordering stuff that's not critical

Expressions are sorted by length/number of sub-terms, then alphabetically. I don't know what ordering exactly you'd like to see changed but to set expectations, the algorithm cannot order them in a way that resembles the input logic format in any way; expression equality checking completely normalizes the requirements.

The one remaining thing is maybe extending the tooltips to entrance labels. The code computes requirement expressions for them but the UI doesn't use them yet.

**Comment by CovenEsme** [comment]
The requirement I was interested in was this one
image

To me, I'd expect the expression containing the Practice Sword to be listed last because it has more sub-expressions than the Goddess Sword one and comes last alphabetically (does the alphabetical sorting use the pretty names?)

**Comment by CovenEsme** [comment]
Latest commit orders the expressions more complex expressions I was looking at as I'd expect :p

**Review by CovenEsme — APPROVED** [review]

**Pull request merged**
